Enhancement - Added Logo and banner url from asset path
surecart/wordpress-sdk pull request #9
Opened 2024-02-02 08:56 UTC by ManiruzzamanAkash

## Issue
WordPress SDK -  Add ability to add logo to licensing plugins in the WordPress updates section.

Fixes [SC-3447](https://brainstormforce.atlassian.net/browse/SC-3447)

## Video
https://d.pr/v/yQwMcc

2025-04-15 13:24 UTC, Tropicalista commented
Any chance to merge this?

2026-04-15 13:26 UTC, ajgagnon requested changes

2026-04-15 13:26 UTC, ajgagnon commented on src/Updater.php
> +				if ( $this->urlExists( $image_url ) ) {
Let's not check this - it's going to cause a server request for each image, which can slow things down. It will also hide any broken images and make troubleshooting more confusing. 

Instead, we should just serve the image

2026-04-15 13:26 UTC, ajgagnon commented on src/Updater.php
> +					$images[ $size ] = $image_url;
Let's `esc_url_raw` here just in case.

2026-04-15 19:10 UTC, merged